### ISSUE TITLE
segmentfault上的demo链接进去后没有效果

### ISSUE THREAD

**Issue by sunlianlong** [lonelymoon/DanMuer#1]
如题，链接进入后如下图，看不到视频也看不到弹幕，希望作者能否查一下，谢谢
![image](https://user-images.githubusercontent.com/22101668/28103638-65ebee66-6709-11e7-95ae-4fe1aa5ce497.png)

**Comment by lonelymoon** [comment]
@sunlianlong  我可能没有把使用方法写清楚，等下我去改下文章。
操作方法是这样的：
你先添加好普通弹幕后，可以是10000条，多点没关系，别太多就行，然后点下拉框-》点选“控制项”这一栏，然后点击启动就好了

**Comment by longhonour** [comment]
有es5版本源码么？

**Comment by lonelymoon** [comment]
@longhonour 并没有，es5版本是通过babel转的，其实学代码学原理就行了。es5版我以前写过一个弹幕播放器2.0版本，带视频播放器的 ，在我的projects那个库里面，你可以下载来看看，那个是es5版本的
