### ISSUE TITLE
普通弹幕还差个属性吧？

### ISSUE THREAD

**Issue by hkongm** [lonelymoon/DanMuer#3]
`time` 是咋来的？

文档里没写，demo 和 源码里有

定义弹幕出现的时间点么？时间与播放时间相关？毫秒？

**Comment by lonelymoon** [comment]
没有啊，你说的那个time应该是被提取到外部的一个属性，不是插件内造成影响的一个属性。。
time这里应该是作为一个由用户自己附加的一个属性用于判断弹幕进场时间，至于出现的时间点是由用户自己做判断的，在外部进行判断到了特定时间后，调用inputData插入弹幕就行了。。这个不是内部属性，我特意把判断条件都提取到外部进行解耦。
